spring:
  cache:
    type: simple
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5433/weather_db
    username: user
    password: user
  flyway:
    enabled: true
    locations: classpath:db/migration

openweathermap:
  api:
    key: ${weather.api.key:}
    url: https://api.openweathermap.org/data/2.5/weather

logging:
  level:
    org.springframework: INFO