#spring.datasource.url=jdbc:h2:file:./data/mydb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=validate
#spring.h2.console.enabled=true


#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/weather_db
#    username: user
#    password: user
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#  flyway:
#    enabled: true
#    locations: classpath:db/migration



  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/weather_db
      username: user
      password: user
    flyway:
      enabled: true
      locations: classpath:db/migration